// This is your database. 
// You can add new words here without touching the main app code.
const APP_DATA = [
    {
    code: "de-DE",
    name: "Deutsch",
    datasets: [
        {
            "name": "Wörter 17 bis 32",
            "items": [
                "Sie verschieben es auf morgen.",
                "Ich habe ihn noch nie gesehen.",
                "Tobias überquert die Strasse.",
                "Sie geht mit ihrem Vater angeln.",
                "Julia hält ihn fest.",
                "Das Buch ist sehr spannend.",
                "Ich weiss nicht, wo er ist.",
                "Es wäre schön, wenn es klappen würde.",
                "Im Käfig sass ein bunter Vogel.",
                "Jeder bekommt eine Tafel Schokolade.",
                "Holger hat sich ziemlich aufgeregt.",
                "Sie sitzt in ihrem Sessel und denkt nach.",
                "Jonas gibt nie etwas ab.",
                "Im Garten steht ein grosser Kirschbaum.",
                "Die Kinder sind alle gekommen.",
                "Sie nehmen, was sie bekommen können."
            ]
        },
        {
            name: "Fehlerwörter 300",
            items: [
                "Wie gross ist er?",
                "Wir sind bald am Ziel.",
                "Sie ist schon wieder da.",
                "Und dann brachen wir auf.",
                "Sie fahren über eine Brücke.",
                "Einmal versuchen wir es noch.",
                "Jens schaute nicht zurück.",
                "Die Hausaufgaben sind fertig.",
                "Lars kommt die Treppe herauf.",
                "Sie hat gewonnen.",
                "Vom Dach fallen Tropfen.",
                "Willi liess mich nicht in Ruhe.",
                "Ich habe es ihm schon einmal gesagt.",
                "Sie liefen plötzlich weg.",
                "Kerstin war sehr fleissig.",
                "Die Kinder sehen sich einen Film an.",
                "Sie verschieben es auf morgen.",
                "Ich habe ihn noch nie gesehen.",
                "Tobias überquert die Strasse.",
                "Sie geht mit ihrem Vater angeln.",
                "Julia hält ihn fest.",
                "Das Buch ist sehr spannend.",
                "Ich weiss nicht, wo er ist.",
                "Es wäre schön, wenn es klappen würde.",
                "Im Käfig sass ein bunter Vogel.",
                "Jeder bekommt eine Tafel Schokolade.",
                "Holger hat sich ziemlich aufgeregt.",
                "Sie sitzt in ihrem Sessel und denkt nach.",
                "Jonas gibt nie etwas ab.",
                "Im Garten steht ein grosser Kirschbaum.",
                "Die Kinder sind alle gekommen.",
                "Sie nehmen, was sie bekommen können.",
                "Ich muss mein Zimmer noch aufräumen.",
                "Wir haben heute viel gearbeitet.",
                "Margit band dem Kind die Schuhe zu.",
                "Hubert schaute ihn ohne Furcht an.",
                "Alles hat ein Ende, nur die Wurst hat zwei.",
                "Der Baum fällt gleich um.",
                "Sie hat uns ein bisschen geärgert.",
                "Alexander spielt mit seiner Eisenbahn.",
                "Unser Lehrer ist sehr nett.",
                "Sven schloss schnell die Tür.",
                "Ulla ist jetzt meine Freundin.",
                "Ich hatte es ganz vergessen.",
                "Er kommt nicht mit.",
                "Wir bleiben hier.",
                "Er rennt so schnell er kann.",
                "Sie fährt gleich nach Hause.",
                "Das lassen wir uns nicht gefallen.",
                "Die Hütte sieht ziemlich alt aus.",
                "Das Mädchen heisst Christine.",
                "Sie verbrachten die Ferien zu Hause.",
                "Er soll ein Auto gestohlen haben.",
                "Bist du sicher, dass dies der richtige Ort ist?",
                "Seine Mutter fährt das Auto in die Garage.",
                "Mir fehlt nichts.",
                "Sie haben sich endlich entschieden.",
                "Der Hund läuft los.",
                "Er nahm sich viel Zeit für uns.",
                "Katja rief mir etwas zu.",
                "Sie lachten ihn aus.",
                "Tobias kam uns zur Hilfe.",
                "Fabian geht einkaufen.",
                "Er kauft sich ein Radio, wenn er wieder Geld hat.",
                "Wir haben alles auf einmal erledigt.",
                "Die Grube war voll Wasser.",
                "Sie bog in die nächste Strasse ein.",
                "Dennis nimmt sich ein paar Kekse.",
                "Von aussen sah der Apfel sehr lecker aus.",
                "Es wird immer schwieriger.",
                "Sandra hat es uns nämlich nicht gesagt.",
                "Alle wissen es.",
                "Jeder kriegt ein Stück Kuchen.",
                "Jasmin sah mich lachend an.",
                "Konnte man ihnen nicht helfen?",
                "Jeden Tag musste er früh aufstehen.",
                "Er hat immer die Wahrheit gesagt.",
                "Sie haben keine Kraft mehr.",
                "Warum sagt er so etwas?",
                "Ich kann Laura gut leiden.",
                "Manuel stellt den alten Schrank in den Keller.",
                "Ich wünsche mir ein blaues Fahrrad.",
                "Tobias ist wieder ganz gesund.",
                "Sie sahen am Abend fern.",
                "Er bekam viele Geschenke.",
                "Anika fuhr allein nach Köln.",
                "Er fiel die Treppe hinunter.",
                "Malte isst sich satt.",
                "Er ging zum Fussballplatz.",
                "Der Indianer schlich sich ganz nah an seine Feinde heran.",
                "Das hätte auch nichts genützt.",
                "Sie half ihm aus dem Mantel.",
                "Heidi kennt mich nicht.",
                "Er hat es vielleicht schon erraten.",
                "Toni lässt uns nicht hinein.",
                "Sie stand vor dem Fenster.",
                "David fragt nach, denn er hat es nicht verstanden.",
                "Sie hat nur wenig Vertrauen zu uns.",
                "Er will es gar nicht wissen.",
                "Vor der Schule stehen viele Fahrräder.",
                "Sabine hat ein Glas zerbrochen.",
                "Kühe fressen Gras.",
                "Wovor hat er Angst?",
                "Ich war ganz erschrocken.",
                "Jens liest gerade die Zeitung.",
                "Er stand in der Mitte des Tores.",
                "Das hat er mir anders erzählt.",
                "Wir setzen uns an den Tisch.",
                "Das Reh flüchtete in den Wald.",
                "Sie gucken uns nicht an.",
                "Er stiess mit dem Fuss gegen einen Stein.",
                "Wer wagt, der gewinnt.",
                "Der Mond schien hell.",
                "Seine beste Zeit ist vorbei.",
                "Sie zieht ihn an den Haaren.",
                "Wenn er sich Mühe gibt, trifft er auch.",
                "Er schnitt ein Stück von der Wurst ab.",
                "Artur möchte zur Polizei.",
                "Meine Jacke ist ganz nass.",
                "Der Film war überhaupt nicht lustig.",
                "Die Tüte ist leer.",
                "Birgit wünscht sich eine Katze.",
                "Der Hund bewacht das Haus.",
                "Das Zebra frass mir aus der Hand.",
                "Sie versuchten einen Schatz zu entdecken.",
                "Das war schon der dritte Fehler.",
                "Der Schüler schrieb eine Zahl in sein Heft.",
                "Der Weg führt durch den Wald.",
                "Draussen stehen vier Autos.",
                "Herr Meier ist ungefähr sechzig Jahre alt.",
                "Er erzählte etwas von einem Tier.",
                "Die Stimme kommt mir bekannt vor.",
                "Sie ist selbst gekommen.",
                "Das Schloss klemmte.",
                "Wir sind noch lange nicht satt.",
                "Ich stand in der zehnten Reihe.",
                "Tim ging erst spät ins Bett.",
                "Er kämmte sich die Haare, nachdem er geduscht hatte.",
                "Sie beisst den Faden ab.",
                "An der Decke hängt eine Lampe.",
                "Wir spielen abends manchmal Halma.",
                "Neben mir ist noch ein Platz frei.",
                "Andrea hielt ihre Augen offen.",
                "Dort ist niemand.",
                "Er liegt auf dem Sofa.",
                "Ein Jahr hat zwölf Monate.",
                "Sie heisst Tatjana.",
                "Sind sie wirklich glücklich?",
                "Sie haben zusammen gearbeitet.",
                "Matthias verliert immer sein Geld.",
                "Das Lied, das er sang, war sehr traurig.",
                "Plötzlich war es still.",
                "Der Eingang ist rechts.",
                "Die Puppe hat schöne Haare.",
                "Er kam ganz nah heran.",
                "Boris passt gut auf.",
                "Diese Aufgabe geht so ähnlich, wie die vorherige.",
                "Das war nicht sehr klug von dir.",
                "Wer hat eine Idee?",
                "Dort kommt Herr Neumann.",
                "Er hielt mich mit einer Hand fest.",
                "Er hat im Gefängnis gesessen.",
                "Sie führt uns durch die engen Strassen.",
                "Was hat er eigentlich angestellt?",
                "Es ist bald zehn Uhr.",
                "Wir hoffen auf besseres Wetter.",
                "Die Maus ist tot.",
                "Er hat einen Sohn und eine Tochter.",
                "Paul schrie, wie am Spiess.",
                "Der Ball ist rund.",
                "Steffen reisst die Tüte auf.",
                "Meist ist man hinterher klüger als vorher.",
                "Wir traten in das Geschäft ein.",
                "Es ist noch früh.",
                "Er ist dünn, wie eine Bohnenstange.",
                "Auf meinen Freund kann ich mich verlassen.",
                "Man kann krank davon werden.",
                "Er braucht etwas Geld.",
                "Es ist kalt und ausserdem regnet es.",
                "Unsere Familie besteht aus vier Personen.",
                "Patrick geht in die zweite Klasse.",
                "Sie war häufig bei uns zu Gast.",
                "Miriam wohnt bei ihren Grosseltern.",
                "Überall lag Schnee.",
                "Sie wollten es uns verbieten.",
                "An der Wand hing eine Uhr.",
                "Wir haben den Ball überall gesucht.",
                "Sie stossen ihn die Treppe hinunter.",
                "Sie schimpfen die Kinder aus.",
                "Auf dem Flur ist es ganz ruhig.",
                "Elvira sprach, obwohl ihr keiner zuhörte.",
                "Sie nennt ihren Namen nicht.",
                "Der Schüler las einen Satz vor.",
                "Das Auto ist schon lange kaputt.",
                "Jeremias hat mir einen Brief geschrieben.",
                "Sie haben keinen Pfennig Geld.",
                "Andreas erzählt, was er erlebt hat.",
                "Philipp sammelt Briefmarken.",
                "Die Katze lag auf einer Decke.",
                "Der Lehrer möchte die fleissigen Schüler belohnen.",
                "Es hat ihn bisher nicht gestört.",
                "Ich habe einen Augenblick nicht aufgepasst.",
                "Wir müssen die Birne noch aus der Lampe drehen.",
                "Er versuchte, uns die Aufgabe zu erklären.",
                "Ich helfe dir, falls es nötig ist.",
                "Das hat er sich wohl geirrt.",
                "Er vergisst manchmal seine Tasche.",
                "Das Loch ist noch nicht tief genug.",
                "Im letzten Sommer hat es oft geregnet.",
                "Konrad hat alles richtig gemacht.",
                "Margarete steht links neben Jakob.",
                "Ihr Kleid hat einen Fleck.",
                "Wann hast du Geburtstag?",
                "Ich glaube, ich habe einen Fehler gemacht.",
                "Das Haus war noch älter als ich dachte.",
                "Da ist doch nichts dabei.",
                "Helena braucht bald eine Brille.",
                "Die Rüben stecken in der Erde.",
                "Es wird bestimmt nicht regnen.",
                "Das war wirklich schwierig.",
                "Das Wasser ist ganz trübe.",
                "Ich kann dich nicht verstehen.",
                "Es ist nie zu spät.",
                "Sie probieren die neuen Kleider an.",
                "Er konnte vor Schreck nichts sagen.",
                "Am Nachmittag schien die Sonne.",
                "Heidrun schickt die Kinder weg.",
                "Sie versuchte, sich zu ändern.",
                "Lukas stieg in die Bahn ein.",
                "Sie hat es schliesslich doch noch versucht.",
                "Ich kannte den Mann nicht.",
                "Seid ihr hungrig?",
                "Der Bus war schon weg.",
                "Ich glaube, sie schafft es.",
                "Ich habe gar kein Geld.",
                "Lisa möchte ein Eis.",
                "Sie öffnete den Brief.",
                "Sabrina setzte sich auf den Stuhl.",
                "Das Rad dreht sich nicht mehr.",
                "Sie nimmt das Telefon und wählt eine Nummer.",
                "Sei doch nicht so ängstlich.",
                "Hat es euch Spass gemacht?",
                "Vielleicht fällt Weihnachten Schnee.",
                "Das Essen schmeckt wirklich gut.",
                "Tom riss das Papier in Streifen.",
                "Der junge Mann sieht recht kräftig aus.",
                "Sie hat eine Tablette genommen.",
                "Wir waren froh, dass er endlich erschien.",
                "Wir freuen uns auf die Ferien.",
                "Warum ist er so dick?",
                "Ich kaufe gerne billig ein.",
                "Das Bild zeigt einen Hirsch.",
                "Esther arbeitete, während Timo schlief.",
                "Die Tasse hatte einen Sprung.",
                "Der Vogel fliegt weg.",
                "Ich glaube, sie wollen uns ärgern.",
                "Oliver bezahlt an der Kasse.",
                "Die Ente schwimmt auf dem Teich.",
                "Er hatte das Erlebnis schon fast vergessen.",
                "Judith giesst sich ein Glas Milch ein.",
                "An dieser Stelle blieb das Auto liegen.",
                "Obst und Gemüse sind gesund.",
                "Antonio schiebt sein Fahrrad hinter das Haus.",
                "Die Sonne verschwand hinter den Wolken.",
                "Ich erschrak, als ich ihn sah.",
                "Gib mir bitte ein Glas Wasser.",
                "Wir müssen aufpassen, dass nichts passiert.",
                "Ich wusste es schon, bevor er es mir verriet.",
                "Das war wirklich schlimm.",
                "Sie sass auf einem Stein.",
                "Der Halm biegt sich im Wind.",
                "Das ist doch nicht wahr.",
                "Der Ausflug hat uns gut gefallen.",
                "Wir müssen bald Schluss machen.",
                "Er ist gelb wie eine Zitrone.",
                "Das ist ihr bestimmt nicht recht.",
                "Ich war natürlich zuletzt dran.",
                "Das Wasser fliesst die Wand hinunter.",
                "Elvira malte ein Haus auf ein grosses Blatt.",
                "Die Geschichte hört sich schrecklich an.",
                "Ich will es ihnen nicht befehlen.",
                "Der Schuh drückt.",
                "Sein Mantel war weiss.",
                "Diana stellte einen Teller auf den Tisch.",
                "Draussen brennt es.",
                "Sie möchten in Frieden leben.",
                "Wir wohnen oben auf einem Berg.",
                "Daniel fuhr mit dem Schiff nach Amerika.",
                "Sie messen aus, wie lang der Baum ist.",
                "Die Leute gehen am Fluss entlang spazieren.",
                "Oma lässt herzlich grüssen.",
                "Kannst du auf den Baum klettern?",
                "Warum hat er bloss nichts gesagt?",
                "Im Urwald ist es gefährlich.",
                "Hans glaubt, dass er meistens recht hat.",
                "Der Himmel ist blau.",
                "Das Beispiel habe ich nicht verstanden.",
                "Es kann nur noch besser werden.",
                "Auf dem Tisch lagen ein paar Tomaten.",
                "Sie ass einen Pfannkuchen."]
            },
//            { 
//                name: "Tiere und Natur", 
//                items: [
//                    "Der Hund spielt im Garten.", 
//                    "Die Katze schläft auf dem Sofa.", 
//                    "Der Vogel singt ein schönes Lied.",
//                    "Der Elefant ist sehr gross."
//                ] 
//            },
//            { 
//                name: "Schule und Alltag", 
//                items: [
//                    "Ich gehe gerne in die Schule.", 
//                    "Das Wetter ist heute sehr schön.", 
//                    "Wir lernen heute lesen und schreiben.",
//                    "In der Pause spielen wir Fussball."
//                ] 
//            }
        ]
    },
    {
        code: "en-GB",
        name: "English",
        datasets: [
            { 
                name: "Animals", 
                items: ["The cat sat on the mat.", "A big elephant.", "The dog barks."] 
            },
            { 
                name: "Nature", 
                items: ["The sun is very bright.", "The grass is green.", "Rain falls from clouds."] 
            }
        ]
    },
    {
        code: "fr-FR",
        name: "Français",
        datasets: [
            { 
                name: "Base", 
                items: ["Bonjour tout le monde.", "Le chat est noir.", "Il fait beau aujourd'hui."] 
            }
        ]
    }
];
