// words.js
const dictionary = [
    // Family & People
    { en: "Granddaughter", sr: "Unuka", category: "Family" },
    { en: "Husband", sr: "Muž", category: "Family" },
    { en: "Sister", sr: "Sestra", category: "Family" },
    { en: "Friend", sr: "Prijatelj", category: "People" },
    { en: "Doctor", sr: "Lekar", category: "People" },
    
    // Food & Drink
    { en: "Breakfast", sr: "Doručak", category: "Food" },
    { en: "Lunch", sr: "Ručak", category: "Food" },
    { en: "Dinner", sr: "Večera", category: "Food" },
    { en: "Coffee", sr: "Kafa", category: "Drink" },
    { en: "Tea", sr: "Čaj", category: "Drink" },
    { en: "Bread", sr: "Hleb", category: "Food" },
    { en: "Cheese", sr: "Sir", category: "Food" },
    { en: "Apple", sr: "Jabuka", category: "Fruit" },
    
    // Home & Daily
    { en: "House", sr: "Kuća", category: "Home" },
    { en: "Key", sr: "Ključ", category: "Objects" },
    { en: "Phone", sr: "Telefon", category: "Objects" },
    { en: "Window", sr: "Prozor", category: "Home" },
    { en: "Door", sr: "Vrata", category: "Home" },
    { en: "Bed", sr: "Krevet", category: "Home" },
    
    // Feelings & Nature
    { en: "Happy", sr: "Srećna", category: "Emotion" }, 
    { en: "Tired", sr: "Umorna", category: "Emotion" },
    { en: "Sun", sr: "Sunce", category: "Nature" },
    { en: "Rain", sr: "Kiša", category: "Nature" },
    { en: "Cold", sr: "Hladno", category: "Weather" },
    { en: "Hot", sr: "Vruće", category: "Weather" },

    // Verbs (Actions)
    { en: "To walk", sr: "Šetati", category: "Action" },
    { en: "To sleep", sr: "Spavati", category: "Action" },
    { en: "To eat", sr: "Jesti", category: "Action" },
    { en: "To see", sr: "Videti", category: "Action" },

    // --- THE HOUSE (KUĆA) ---
    { en: "Kitchen", sr: "Kuhinja", category: "House" },
    { en: "Living room", sr: "Dnevna soba", category: "House" },
    { en: "Bedroom", sr: "Spavaća soba", category: "House" },
    { en: "Bathroom", sr: "Kupatilo", category: "House" },
    { en: "Balcony", sr: "Terasa", category: "House" },
    { en: "Door", sr: "Vrata", category: "House" },
    { en: "Window", sr: "Prozor", category: "House" },
    { en: "Floor", sr: "Pod", category: "House" },
    { en: "Wall", sr: "Zid", category: "House" },
    { en: "Roof", sr: "Krov", category: "House" },
    { en: "Garden", sr: "Bašta", category: "House" },
    { en: "Stairs", sr: "Stepenice", category: "House" },

    // --- FURNITURE (NAMEŠTAJ) ---
    { en: "Table", sr: "Sto", category: "Furniture" },
    { en: "Chair", sr: "Stolica", category: "Furniture" },
    { en: "Armchair", sr: "Fotelja", category: "Furniture" },
    { en: "Sofa", sr: "Kauč", category: "Furniture" },
    { en: "Bed", sr: "Krevet", category: "Furniture" },
    { en: "Wardrobe", sr: "Ormar", category: "Furniture" },
    { en: "Lamp", sr: "Lampa", category: "Furniture" },
    { en: "Carpet", sr: "Tepih", category: "Furniture" },
    { en: "Mirror", sr: "Ogledalo", category: "Furniture" },
    { en: "Curtain", sr: "Zavesa", category: "Furniture" },

    // --- KITCHEN & UTENSILS (KUHINJA) ---
    { en: "Fridge", sr: "Frižider", category: "Kitchen" },
    { en: "Stove", sr: "Šporet", category: "Kitchen" },
    { en: "Oven", sr: "Rerna", category: "Kitchen" },
    { en: "Sink", sr: "Sudopera", category: "Kitchen" },
    { en: "Plate", sr: "Tanjir", category: "Kitchen" },
    { en: "Glass", sr: "Čaša", category: "Kitchen" },
    { en: "Cup", sr: "Šolja", category: "Kitchen" },
    { en: "Fork", sr: "Viljuška", category: "Kitchen" },
    { en: "Spoon", sr: "Kašika", category: "Kitchen" },
    { en: "Knife", sr: "Nož", category: "Kitchen" },
    { en: "Pan", sr: "Tiganj", category: "Kitchen" },
    { en: "Pot", sr: "Šerpa", category: "Kitchen" },
    { en: "Bowl", sr: "Činija", category: "Kitchen" },
    { en: "Napkin", sr: "Salveta", category: "Kitchen" },
    { en: "Bottle", sr: "Flaša", category: "Kitchen" },

    // --- FOOD (HRANA) ---
    { en: "Bread", sr: "Hleb", category: "Food" },
    { en: "Meat", sr: "Meso", category: "Food" },
    { en: "Chicken", sr: "Piletina", category: "Food" },
    { en: "Fish", sr: "Riba", category: "Food" },
    { en: "Egg", sr: "Jaje", category: "Food" },
    { en: "Cheese", sr: "Sir", category: "Food" },
    { en: "Soup", sr: "Supa", category: "Food" },
    { en: "Salad", sr: "Salata", category: "Food" },
    { en: "Rice", sr: "Pirinač", category: "Food" },
    { en: "Pasta", sr: "Testenina", category: "Food" },
    { en: "Butter", sr: "Puter", category: "Food" },
    { en: "Oil", sr: "Ulje", category: "Food" },
    { en: "Sugar", sr: "Šećer", category: "Food" },
    { en: "Salt", sr: "So", category: "Food" },
    { en: "Pepper", sr: "Biber", category: "Food" },

    // --- FRUIT & VEGETABLES (VOĆE I POVRĆE) ---
    { en: "Apple", sr: "Jabuka", category: "Fruit" },
    { en: "Banana", sr: "Banana", category: "Fruit" },
    { en: "Orange", sr: "Pomorandža", category: "Fruit" },
    { en: "Lemon", sr: "Limun", category: "Fruit" },
    { en: "Strawberry", sr: "Jagoda", category: "Fruit" },
    { en: "Grapes", sr: "Grožđe", category: "Fruit" },
    { en: "Watermelon", sr: "Lubenica", category: "Fruit" },
    { en: "Potato", sr: "Krompir", category: "Veg" },
    { en: "Tomato", sr: "Paradajz", category: "Veg" },
    { en: "Cucumber", sr: "Krastavac", category: "Veg" },
    { en: "Onion", sr: "Crni luk", category: "Veg" },
    { en: "Garlic", sr: "Beli luk", category: "Veg" },
    { en: "Carrot", sr: "Šargarepa", category: "Veg" },
    { en: "Pepper", sr: "Paprika", category: "Veg" },
    { en: "Beans", sr: "Pasulj", category: "Veg" },
    { en: "Cabbage", sr: "Kupus", category: "Veg" },

    // --- DRINKS (PIĆE) ---
    { en: "Water", sr: "Voda", category: "Drink" },
    { en: "Coffee", sr: "Kafa", category: "Drink" },
    { en: "Tea", sr: "Čaj", category: "Drink" },
    { en: "Milk", sr: "Mleko", category: "Drink" },
    { en: "Juice", sr: "Sok", category: "Drink" },
    { en: "Wine", sr: "Vino", category: "Drink" },
    { en: "Beer", sr: "Pivo", category: "Drink" },
    { en: "Yogurt", sr: "Jogurt", category: "Drink" },

    // --- DAILY OBJECTS (PREDMETI) ---
    { en: "Phone", sr: "Telefon", category: "Object" },
    { en: "Key", sr: "Ključ", category: "Object" },
    { en: "Wallet", sr: "Novčanik", category: "Object" },
    { en: "Bag", sr: "Torba", category: "Object" },
    { en: "Glasses", sr: "Naočare", category: "Object" },
    { en: "Watch", sr: "Sat", category: "Object" },
    { en: "Umbrella", sr: "Kišobran", category: "Object" },
    { en: "Book", sr: "Knjiga", category: "Object" },
    { en: "Pen", sr: "Olovka", category: "Object" },
    { en: "Paper", sr: "Papir", category: "Object" },
    { en: "Newspaper", sr: "Novine", category: "Object" },
    { en: "Towel", sr: "Peškir", category: "Object" },
    { en: "Soap", sr: "Sapun", category: "Object" },

    // --- FAMILY (PORODICA) ---
    { en: "Family", sr: "Porodica", category: "Family" },
    { en: "Mother", sr: "Majka", category: "Family" },
    { en: "Father", sr: "Otac", category: "Family" },
    { en: "Sister", sr: "Sestra", category: "Family" },
    { en: "Brother", sr: "Brat", category: "Family" },
    { en: "Grandmother", sr: "Baka", category: "Family" },
    { en: "Grandfather", sr: "Deka", category: "Family" },
    { en: "Granddaughter", sr: "Unuka", category: "Family" },
    { en: "Grandson", sr: "Unuk", category: "Family" },
    { en: "Daughter", sr: "Ćerka", category: "Family" },
    { en: "Son", sr: "Sin", category: "Family" },
    { en: "Aunt", sr: "Tetka", category: "Family" },
    { en: "Uncle", sr: "Ujak", category: "Family" },
    { en: "Husband", sr: "Muž", category: "Family" },
    { en: "Wife", sr: "Supruga", category: "Family" },
    { en: "Parents", sr: "Roditelji", category: "Family" },
    { en: "Children", sr: "Deca", category: "Family" },

    // --- PEOPLE (LJUDI) ---
    { en: "Friend", sr: "Prijatelj", category: "People" },
    { en: "Neighbor", sr: "Komšija", category: "People" },
    { en: "Guest", sr: "Gost", category: "People" },
    { en: "Man", sr: "Muškarac", category: "People" },
    { en: "Woman", sr: "Žena", category: "People" },
    { en: "Boy", sr: "Dečak", category: "People" },
    { en: "Girl", sr: "Devojčica", category: "People" },
    { en: "Baby", sr: "Beba", category: "People" },
    { en: "Doctor", sr: "Lekar", category: "People" },

    // --- BODY & HEALTH (TELO I ZDRAVLJE) ---
    { en: "Body", sr: "Telo", category: "Body" },
    { en: "Head", sr: "Glava", category: "Body" },
    { en: "Hair", sr: "Kosa", category: "Body" },
    { en: "Face", sr: "Lice", category: "Body" },
    { en: "Eye", sr: "Oko", category: "Body" },
    { en: "Ear", sr: "Uvo", category: "Body" },
    { en: "Nose", sr: "Nos", category: "Body" },
    { en: "Mouth", sr: "Usta", category: "Body" },
    { en: "Tooth", sr: "Zub", category: "Body" },
    { en: "Neck", sr: "Vrat", category: "Body" },
    { en: "Shoulder", sr: "Rame", category: "Body" },
    { en: "Arm", sr: "Ruka", category: "Body" },
    { en: "Hand", sr: "Šaka", category: "Body" },
    { en: "Finger", sr: "Prst", category: "Body" },
    { en: "Stomach", sr: "Stomak", category: "Body" },
    { en: "Back", sr: "Leđa", category: "Body" },
    { en: "Leg", sr: "Noga", category: "Body" },
    { en: "Knee", sr: "Koleno", category: "Body" },
    { en: "Foot", sr: "Stopalo", category: "Body" },
    { en: "Heart", sr: "Srce", category: "Body" },
    { en: "Pain", sr: "Bol", category: "Health" },
    { en: "Medicine", sr: "Lek", category: "Health" },
    { en: "Healthy", sr: "Zdrav", category: "Health" },
    { en: "Sick", sr: "Bolesna", category: "Health" },

    // --- CLOTHING (ODEĆA) ---
    { en: "Clothes", sr: "Odeća", category: "Clothes" },
    { en: "Shirt", sr: "Majica", category: "Clothes" },
    { en: "Blouse", sr: "Bluza", category: "Clothes" },
    { en: "Pants", sr: "Pantalone", category: "Clothes" },
    { en: "Dress", sr: "Haljina", category: "Clothes" },
    { en: "Skirt", sr: "Suknja", category: "Clothes" },
    { en: "Coat", sr: "Kaput", category: "Clothes" },
    { en: "Jacket", sr: "Jakna", category: "Clothes" },
    { en: "Sweater", sr: "Džemper", category: "Clothes" },
    { en: "Shoes", sr: "Cipele", category: "Clothes" },
    { en: "Boots", sr: "Čizme", category: "Clothes" },
    { en: "Socks", sr: "Čarape", category: "Clothes" },
    { en: "Hat", sr: "Kapa", category: "Clothes" },
    { en: "Scarf", sr: "Šal", category: "Clothes" },
    { en: "Gloves", sr: "Rukavice", category: "Clothes" },
    { en: "Slippers", sr: "Papuče", category: "Clothes" },
    { en: "Pocket", sr: "Džep", category: "Clothes" },
    { en: "Button", sr: "Dugme", category: "Clothes" },

    // --- NATURE & WEATHER (PRIRODA) ---
    { en: "Sun", sr: "Sunce", category: "Nature" },
    { en: "Moon", sr: "Mesec", category: "Nature" },
    { en: "Sky", sr: "Nebo", category: "Nature" },
    { en: "Star", sr: "Zvezda", category: "Nature" },
    { en: "Cloud", sr: "Oblak", category: "Nature" },
    { en: "Rain", sr: "Kiša", category: "Nature" },
    { en: "Snow", sr: "Sneg", category: "Nature" },
    { en: "Wind", sr: "Vetar", category: "Nature" },
    { en: "Tree", sr: "Drvo", category: "Nature" },
    { en: "Flower", sr: "Cvet", category: "Nature" },
    { en: "Grass", sr: "Trava", category: "Nature" },
    { en: "River", sr: "Reka", category: "Nature" },
    { en: "Sea", sr: "More", category: "Nature" },
    { en: "Mountain", sr: "Planina", category: "Nature" },
    { en: "Forest", sr: "Šuma", category: "Nature" },

    // --- ANIMALS (ŽIVOTINJE) ---
    { en: "Animal", sr: "Životinja", category: "Animals" },
    { en: "Dog", sr: "Pas", category: "Animals" },
    { en: "Cat", sr: "Mačka", category: "Animals" },
    { en: "Bird", sr: "Ptica", category: "Animals" },
    { en: "Fish", sr: "Riba", category: "Animals" },
    { en: "Chicken", sr: "Kokoška", category: "Animals" },
    { en: "Cow", sr: "Krava", category: "Animals" },
    { en: "Pig", sr: "Svinja", category: "Animals" },
    { en: "Horse", sr: "Konj", category: "Animals" },
    { en: "Mouse", sr: "Miš", category: "Animals" },
    { en: "Bee", sr: "Pčela", category: "Animals" },

    // --- VERBS / ACTIONS (GLAGOLI) ---
    { en: "To go", sr: "Ići", category: "Verbs" },
    { en: "To come", sr: "Doći", category: "Verbs" },
    { en: "To walk", sr: "Šetati", category: "Verbs" },
    { en: "To run", sr: "Trčati", category: "Verbs" },
    { en: "To sit", sr: "Sedeti", category: "Verbs" },
    { en: "To sleep", sr: "Spavati", category: "Verbs" },
    { en: "To wake up", sr: "Probuditi se", category: "Verbs" },
    { en: "To eat", sr: "Jesti", category: "Verbs" },
    { en: "To drink", sr: "Piti", category: "Verbs" },
    { en: "To cook", sr: "Kuvati", category: "Verbs" },
    { en: "To wash", sr: "Prati", category: "Verbs" },
    { en: "To clean", sr: "Čistiti", category: "Verbs" },
    { en: "To buy", sr: "Kupiti", category: "Verbs" },
    { en: "To pay", sr: "Platiti", category: "Verbs" },
    { en: "To work", sr: "Raditi", category: "Verbs" },
    { en: "To read", sr: "Čitati", category: "Verbs" },
    { en: "To write", sr: "Pisati", category: "Verbs" },
    { en: "To speak", sr: "Pričati", category: "Verbs" },
    { en: "To listen", sr: "Slušati", category: "Verbs" },
    { en: "To see", sr: "Videti", category: "Verbs" },
    { en: "To look", sr: "Gledati", category: "Verbs" },
    { en: "To know", sr: "Znati", category: "Verbs" },
    { en: "To want", sr: "Želeti", category: "Verbs" },
    { en: "To love", sr: "Voleti", category: "Verbs" },
    { en: "To help", sr: "Pomoći", category: "Verbs" },

    // --- ADJECTIVES / DESCRIPTION (OPIS) ---
    { en: "Good", sr: "Dobro", category: "Adj" },
    { en: "Bad", sr: "Loše", category: "Adj" },
    { en: "Big", sr: "Veliko", category: "Adj" },
    { en: "Small", sr: "Malo", category: "Adj" },
    { en: "Hot", sr: "Vruće", category: "Adj" },
    { en: "Cold", sr: "Hladno", category: "Adj" },
    { en: "New", sr: "Novo", category: "Adj" },
    { en: "Old", sr: "Staro", category: "Adj" },
    { en: "Beautiful", sr: "Lepo", category: "Adj" },
    { en: "Ugly", sr: "Ružno", category: "Adj" },
    { en: "Happy", sr: "Srećna", category: "Adj" },
    { en: "Sad", sr: "Tužna", category: "Adj" },
    { en: "Tired", sr: "Umorna", category: "Adj" },
    { en: "Clean", sr: "Čisto", category: "Adj" },
    { en: "Dirty", sr: "Prljavo", category: "Adj" },
    { en: "Expensive", sr: "Skupo", category: "Adj" },
    { en: "Cheap", sr: "Jeftino", category: "Adj" },
    { en: "Full", sr: "Puno", category: "Adj" },
    { en: "Empty", sr: "Prazno", category: "Adj" },
    { en: "Open", sr: "Otvoreno", category: "Adj" },
    { en: "Closed", sr: "Zatvoreno", category: "Adj" },

    // --- CITY & PLACES (GRAD I MESTA) ---
    { en: "City", sr: "Grad", category: "Place" },
    { en: "Street", sr: "Ulica", category: "Place" },
    { en: "House", sr: "Kuća", category: "Place" },
    { en: "Building", sr: "Zgrada", category: "Place" },
    { en: "Shop", sr: "Prodavnica", category: "Place" },
    { en: "Market", sr: "Pijaca", category: "Place" },
    { en: "Pharmacy", sr: "Apoteka", category: "Place" },
    { en: "Hospital", sr: "Bolnica", category: "Place" },
    { en: "Bank", sr: "Banka", category: "Place" },
    { en: "Post Office", sr: "Pošta", category: "Place" },
    { en: "Park", sr: "Park", category: "Place" },
    { en: "Bus Station", sr: "Stanica", category: "Place" },
    { en: "Airport", sr: "Aerodrom", category: "Place" },
    { en: "Restaurant", sr: "Restoran", category: "Place" },
    { en: "School", sr: "Škola", category: "Place" },

    // --- TIME (VREME) ---
    { en: "Time", sr: "Vreme", category: "Time" },
    { en: "Day", sr: "Dan", category: "Time" },
    { en: "Night", sr: "Noć", category: "Time" },
    { en: "Morning", sr: "Jutro", category: "Time" },
    { en: "Evening", sr: "Veče", category: "Time" },
    { en: "Week", sr: "Nedelja", category: "Time" },
    { en: "Month", sr: "Mesec", category: "Time" },
    { en: "Year", sr: "Godina", category: "Time" },
    { en: "Now", sr: "Sada", category: "Time" },
    { en: "Later", sr: "Kasnije", category: "Time" },
    { en: "Yesterday", sr: "Juče", category: "Time" },
    { en: "Today", sr: "Danas", category: "Time" },
    { en: "Tomorrow", sr: "Sutra", category: "Time" },

    // --- COLORS & NUMBERS (BOJE I BROJEVI) ---
    { en: "Red", sr: "Crvena", category: "Color" },
    { en: "Blue", sr: "Plava", category: "Color" },
    { en: "Green", sr: "Zelena", category: "Color" },
    { en: "Yellow", sr: "Žuta", category: "Color" },
    { en: "White", sr: "Bela", category: "Color" },
    { en: "Black", sr: "Crna", category: "Color" },
    { en: "One", sr: "Jedan", category: "Number" },
    { en: "Two", sr: "Dva", category: "Number" },
    { en: "Three", sr: "Tri", category: "Number" },
    { en: "Four", sr: "Četiri", category: "Number" },
    { en: "Five", sr: "Pet", category: "Number" },
    { en: "Ten", sr: "Deset", category: "Number" },
    { en: "Twenty", sr: "Dvadeset", category: "Number" },
    { en: "Hundred", sr: "Sto", category: "Number" }
];
